### ISSUE TITLE
Can't run compile-proto.sh

### ISSUE THREAD

**Issue by MertIV** [badsyntax/grpc-js-typescript#34]
Hello, thanks for the effort you've been giving to this project. Its been really helpful for me.

But I couldn't generate proto files from the script you've written in windows even though bash is installed. Can you help me with that?

**Comment by MertIV** [comment]
Hi the current error I'm getting is 

PS C:\Users\mrtkr\Documents\GitHub\grpc-js-typescript\examples\ts-protoc-gen> node_modules/.bin/grpc_tools_node_protoc -I="./" --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts --plugin=protoc-gen-grpc=./node_modules/.bin/protoc-gen-grpc --js_out=import_style=commonjs:. --grpc_out=grpc_js:. --ts_out=grpc_js:. ./proto/example.proto
C:\Users\mrtkr\Documents\GitHub\grpc-js-typescript\examples\ts-protoc-gen\node_modules\grpc-tools\bin\protoc.js:41
    throw error;
    ^

Error: Command failed: C:\Users\mrtkr\Documents\GitHub\grpc-js-typescript\examples\ts-protoc-gen\node_modules\grpc-tools\bin\protoc.exe --plugin=protoc-gen-grpc=C:\Users\mrtkr\Documents\GitHub\grpc-js-typescript\examples\ts-protoc-gen\node_modules\grpc-tools\bin\grpc_node_plugin.exe -I=./ --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts --plugin=protoc-gen-grpc=./node_modules/.bin/protoc-gen-grpc --js_out=import_style=commonjs:. --grpc_out=grpc_js:. --ts_out=grpc_js:. ./proto/example.proto

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 3221225477,
  signal: null,
  cmd: 'C:\\Users\\mrtkr\\Documents\\GitHub\\grpc-js-typescript\\examples\\ts-protoc-gen\\node_modules\\grpc-tools\\bin\\protoc.exe --plugin=protoc-gen-grpc=C:\\Users\\mrtkr\\Documents\\GitHub\\grpc-js-typescript\\examples\\ts-protoc-gen\\node_modules\\grpc-tools\\bin\\grpc_node_plugin.exe -I=./ --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts --plugin=protoc-gen-grpc=./node_modules/.bin/protoc-gen-grpc --js_out=import_style=commonjs:. --grpc_out=grpc_js:. --ts_out=grpc_js:. ./proto/example.proto'
}

Like this I've tried to modify the script but I couldn't run it successfully

**Comment by badsyntax** [comment]
Apologies for the belated response. I'll add some windows scripts to help with this when i get some time, in the meantime have you tried using the [grpc-proto-loaded](https://github.com/badsyntax/grpc-js-typescript/tree/master/examples/grpc-proto-loader) as it does not use the proto compiler.

**Comment by MertIV** [comment]
Hello,

Yeah, I've tried it and managed to run successfully thank you. I'll be much
more appreciated if I could run with out the compiler. Thank you again.

24 Kas 2021 Çar 15:17 tarihinde Richard Willis ***@***.***>
şunu yazdı:
